### ISSUE TITLE
Copyleft license?

### ISSUE THREAD

**Issue by Kryptos-FR** [michaelsutton/hwnd-adorner#2]
Hello,

Your GitHub project does not specify a license. So by default it is strongly copyrighted.
On your blog post you wrote that we could use your code freely.

Could you please chose a license for this project (such as public domain, or any copyleft license)?

Thanks a lot

**Comment by michaelsutton** [comment]
I added MIT license to the project, is that OK for you?

**Comment by Kryptos-FR** [comment]
Thanks a lot, that is really helping.
